Wstepna implementacja encji user
interceptor2048/project-jdp-2010-02 pull request #16
Opened 2020-11-04 22:56 UTC by Faralek

2020-11-08 16:39 UTC, CocotierMon commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +@Table(name = "users")
Według ustaleń ze spotkania - nazwy tabel i kolumn piszemy kapitalikami.

2020-11-08 16:44 UTC, CocotierMon commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "id", nullable = true)
nullable = true - pole Id jest już oznaczone za pomocą adnotacji @NotNull, można skreślić wartość nullable,

2020-11-08 16:51 UTC, CocotierMon commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
Wydaje mi się, że encja User powinna być też połączona z encją Order. Co prawda nie wynika to wprost z zaproponowanego diagramu, jednak zamówienie powinno być moim zdaniem przypisane do konkretnej osoby, a konkretna osoba powinna mieć możliwość wglądu w swoje zamówienie.

2020-11-08 16:53 UTC, CocotierMon commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name="status")
Na spotkaniu ustaliliśmy, aby adnotacje umieszczać przy getterach.

2020-11-08 22:48 UTC, CocotierMon approved these changes

2020-11-09 14:10 UTC, agnieszka-f requested changes
Mam drobną uwagę do typów pól - proponowałabym zmienić typ pola status na typ int ponieważ status użytkownika może być 1 lub 0 (zablokowany/niezablokowany) oraz dla pól houseNumber i apartmentNumber także na typ int ponieważ myślę, że nie ma potrzeby stosowania tak dużego zakresu jaki daje typ Long dla pól dotyczących numeru domu/lokalu.

2020-11-09 21:08 UTC, karolinakondziolka commented on src/main/java/com/kodilla/ecommercee/domain/Invoice.java
>      private double sum;
przy wszystkich atrybutach dotyczacych pieniedzy powinnismy stosowac BigDecimal

2020-11-09 21:08 UTC, karolinakondziolka commented on src/main/java/com/kodilla/ecommercee/domain/Invoice.java
> +    public double getSum() {
BigDecimal

2020-11-09 21:08 UTC, karolinakondziolka commented on src/main/java/com/kodilla/ecommercee/domain/Invoice.java
>      private double sum;
ach, ale Ty przeciez nie robiles encji Invoice, wiec chyba te zmiany Cie nie dotycza

2020-11-10 08:17 UTC, Karlos814 commented
> proponowałabym zmienić typ pola status na typ int ponieważ status użytkownika może być 1 lub 0 (zablokowany/niezablokowany)

Jeśli pole status ma mieć tylko dwa możliwe wybory, to może lepiej zastosować boolean.

2020-11-10 23:13 UTC, Faralek commented
Patrząc na plik json status ma zwracać typowo wartość 1 lub 0 więc może jednak niech zostanie Integer a nie boolean

2020-11-11 07:25 UTC, Karlos814 approved these changes

2020-11-12 07:06 UTC, Faralek commented
> Mam drobną uwagę do typów pól - proponowałabym zmienić typ pola status na typ int ponieważ status użytkownika może być 1 lub 0 (zablokowany/niezablokowany) oraz dla pól houseNumber i apartmentNumber także na typ int ponieważ myślę, że nie ma potrzeby stosowania tak dużego zakresu jaki daje typ Long dla pól dotyczących numeru domu/lokalu.

2020-11-12 08:52 UTC, agnieszka-f approved these changes

2020-11-12 08:57 UTC, merged