wstepna implementacja CartController
interceptor2048/project-jdp-2010-02 pull request #2
Opened 2020-10-26 15:53 UTC by Faralek

2020-10-27 20:39 UTC, karolinakondziolka requested changes

2020-10-27 20:39 UTC, karolinakondziolka commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "deleteOrder")
w tej metodzie przy RequestMethod powinno być DELETE a nie PUT

2020-10-27 20:39 UTC, karolinakondziolka commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "deleteProduct")
w tej metodzie przy RequestMethod powinno być DELETE a nie PUT

2020-10-27 20:39 UTC, karolinakondziolka commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "addOrder")
a tutaj powinno być POST;)

2020-10-27 20:39 UTC, karolinakondziolka commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "addProduct")
tu tak jak w metodzie `addOrder()`

2020-10-27 21:09 UTC, Faralek commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "deleteOrder")
Też się nad tym zastanawiałem, w tym przypadku zarówno Orders jak i Products przechowywane są na listach a te 4 metody które tutaj podkreśliłaś odnoszą się do operacji dodawania lub usuwania elementu z istniejącej cały czas listy. Dlatego właśnie zdecydowałem się na użycie RequestMethod.PUT

2020-10-28 09:54 UTC, agnieszka-f approved these changes

2020-10-28 18:47 UTC, merged